set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'

Plugin 'tpope/vim-fugitive'
Plugin 'tpope/vim-surround'
Plugin 'tpope/vim-commentary'
Plugin 'tpope/vim-flagship'
Plugin 'junegunn/fzf.vim'
Plugin 'nathangrigg/vim-beancount'
Plugin 'fatih/vim-go'
Plugin 'airblade/vim-gitgutter'
Plugin 'SirVer/ultisnips'

call vundle#end()

highlight Normal ctermbg=black ctermfg=white
highlight LineNr ctermbg=black ctermfg=white
highlight CursorLineNr ctermbg=black ctermfg=yellow
highlight StatusLine ctermbg=black ctermfg=white
highlight Pmenu ctermbg=black ctermfg=yellow
highlight PmenuSel ctermbg=yellow ctermfg=black
highlight Visual ctermbg=yellow ctermfg=black
highlight DiffAdd ctermbg=black ctermfg=green
highlight DiffChange ctermbg=black ctermfg=yellow
highlight DiffDelete ctermbg=black ctermfg=red
highlight diffAdded ctermbg=black ctermfg=green
highlight diffRemoved ctermbg=black ctermfg=red
highlight diffChanged ctermbg=black ctermfg=yellow
highlight diffFile ctermbg=black ctermfg=lightblue
highlight diffOldFile ctermbg=black ctermfg=magenta
highlight ColorColumn ctermbg=grey
highlight markdownCodeDelimiter ctermbg=black ctermfg=red
highlight markdownHeadingDelimiter ctermbg=black ctermfg=red
highlight markdownH1 ctermbg=black ctermfg=red
highlight markdownH2 ctermbg=black ctermfg=red
highlight markdownH3 ctermbg=black ctermfg=red
highlight markdownH4 ctermbg=black ctermfg=red
highlight markdownH5 ctermbg=black ctermfg=red
highlight markdownH6 ctermbg=black ctermfg=red
highlight ExtraWhitespace ctermbg=red ctermbg=red
match ExtraWhitespace /\s\+$/
autocmd InsertEnter * highlight StatusLine ctermbg=black ctermfg=yellow
autocmd InsertLeave * highlight StatusLine ctermbg=black ctermfg=white

filetype plugin indent on
syntax on                       "turn on syntax highlighting
set backspace=eol,indent,start  "allow backspacing over everything in insert mode
set history=1000                "store lots of :cmdline history
set showcmd                     "show incomplete cmds down the bottom
set showmatch                   "show matching braces
set noshowmode                  "don't show mode
set relativenumber              "show relative line numbers
set number                      "show current line number
set incsearch                   "search as characters are entered
set hlsearch                    "highlight searches by default
set ignorecase                  "Ignore case in search patterns
set smartcase                   "don't ignore case when inserting uppercase characters
set nowrap                      "dont wrap lines
set linebreak                   "wrap lines at convenient points
set wildmode=longest,full       "complete longest common string, then each full match
set wildmenu                    "visual auto complete for command menu
set mouse=c                     "disable mouse
set shiftround                  "round to multiple of shift width when adjusting indentation
set shiftwidth=4                "number of spaces for each step of auto indent
set softtabstop=4               "number of spaces per tab when editing
set tabstop=8                   "number of visual spaces per tab
set expandtab                   "tabs are spaces
set lazyredraw
set noundofile
set noswapfile
set rtp+=~/opt/fzf
set autowrite
set splitright
set splitbelow
set laststatus=2
set showtabline=0
set background=dark
set completeopt=longest,menuone
set conceallevel=0

let mapleader="\<Space>"
let maplocalleader=","

nnoremap gb :Gblame<CR>
nnoremap gl :Commits<CR>
nnoremap gd :Gdiff<CR>
nnoremap ff :call fzf#run(fzf#wrap({'source': 'git ls-files --exclude-standard --others --cached'}))<CR>
nnoremap <C-p> :Files<CR>
nnoremap <C-n> :Buffers<CR>
nnoremap <C-t> :Tags<CR>

nnoremap L :bprevious<CR>
nnoremap H :bnext<CR>
nnoremap <leader>x :bdelete<CR>

nnoremap <leader>n :GitGutterNextHunk<CR>
nnoremap <leader>p :GitGutterPrevHunk<CR>
nnoremap <leader>u :GitGutterUndoHunk<CR>
nnoremap <leader>c :GitGutterPreviewHunk<CR>

nnoremap <Up> <Nop>
nnoremap <Down> <Nop>
nnoremap <Left> <Nop>
nnoremap <Right> <Nop>

nnoremap ı i
nnoremap Y y$

nnoremap <leader>w :w<CR>
nnoremap <leader>q :q<CR>
nnoremap <leader>t :term<CR>
nnoremap <leader>e :Lexplore<CR>
nnoremap <leader>h :nohlsearch<CR>

inoremap jk <esc>
inoremap <C-e> <C-o>$
inoremap <C-a> <C-o>0

function! ToggleWrap()
    if &wrap
        setlocal nowrap
    else
        setlocal wrap
    endif
endfunction

nnoremap <leader>r :call ToggleWrap()<CR>

let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<c-b>"
let g:UltiSnipsJumpBackwardTrigger="<c-z>"

let g:fzf_preview_window = 'up:30%'
let g:fzf_layout = {'left': '30%'}

" by xolox
" https://stackoverflow.com/a/6271254
function! GetVisualSelection()
    " Why is this not a built-in Vim script function?!
    let [line_start, column_start] = getpos("'<")[1:2]
    let [line_end, column_end] = getpos("'>")[1:2]
    let lines = getline(line_start, line_end)
    if len(lines) == 0
        return ''
    endif
    let lines[-1] = lines[-1][: column_end - (&selection == 'inclusive' ? 1 : 2)]
    let lines[0] = lines[0][column_start - 1:]
    return join(lines, "\n")
endfunction

vnoremap <C-g> :<C-U>execute 'VcsJump grep '.GetVisualSelection()<CR>
