set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'

Plugin 'Raimondi/delimitMate'
Plugin 'editorconfig/editorconfig-vim'
Plugin 'Yggdroot/indentLine'
Plugin 'scrooloose/nerdcommenter'
Plugin 'nvie/vim-flake8'
Plugin 'tpope/vim-fugitive'
Plugin 'henrik/vim-indexed-search'
Plugin 'tpope/vim-surround'
Plugin 'godlygeek/csapprox'
Plugin 'NLKNguyen/papercolor-theme'
Plugin 'sjl/badwolf'

call vundle#end()
filetype plugin indent on

"colors
colorscheme badwolf
set background=dark
set t_Co=256

"allow backspacing over everything in insert mode
set backspace=eol,indent,start

"store lots of :cmdline history
set history=1000

"show incomplete cmds down the bottom
set showcmd
"show current mode down the bottom
set showmode

"show relative line numbers
set relativenumber
"show current line number
set number

"display tabs and trailing spaces
set list
set listchars=tab:▷⋅,trail:⋅,nbsp:⋅

"find the next match as we type the search
set incsearch
"highlight searches by default
set hlsearch
"Ignore case in search patterns
set ignorecase
"Override the ignore case option if the search pattern contains upper case characters.
set smartcase

"dont wrap lines
set wrap
"wrap lines at convenient points
set linebreak

"default indent settings
set shiftwidth=4
set softtabstop=4
set expandtab
set autoindent

"folding settings
set foldmethod=indent   "fold based on indent
set foldnestmax=3       "deepest fold is 3 levels
set nofoldenable        "dont fold by default

set wildmode=list:longest   "make cmdline tab completion similar to bash
set wildmenu                "enable ctrl-n and ctrl-p to scroll thru matches

set formatoptions-=o "dont continue comments when pushing o/O

"vertical/horizontal scroll off settings
set scrolloff=3
set sidescrolloff=7
set sidescroll=1

"load ftplugins and indent files
filetype plugin on
filetype indent on

"turn on syntax highlighting
syntax on

"disable mouse
set mouse=c

"show matching braces
set showmatch

"it's good for performance, but idk how
set lazyredraw

au BufNewFile,BufRead *.adoc call s:asciidoc()

function! s:asciidoc()
    set syntax=asciidoc
    set filetype=asciidoc
    set tw=79 
    set formatoptions=tcqn
endfunction

"undo settings
set noundofile

set noswapfile

"always show status line
set laststatus=2

"status line setup
set statusline=%n\ [%f\ %y]    "tail of the filename
set statusline+=%*

"display a warning if fileformat isnt unix
set statusline+=%#warningmsg#
set statusline+=%{&ff!='unix'?'['.&ff.']':''}
set statusline+=%*

"display a warning if file encoding isnt utf-8
set statusline+=%#warningmsg#
set statusline+=%{(&fenc!='utf-8'&&&fenc!='')?'['.&fenc.']':''}
set statusline+=%*

set statusline+=%h      "help file flag

"read only flag
set statusline+=%#identifier#
set statusline+=%r
set statusline+=%*

"modified flag
set statusline+=%#warningmsg#
set statusline+=%m
set statusline+=%*

set statusline+=%{fugitive#statusline()}

set statusline+=%=(%l/%L):%v\ %P

"FLAKE8
let g:flake8_cmd="/usr/bin/flake8-3"

"MAPPINGS
let mapleader="\<Space>"
let maplocalleader=","

nnoremap <leader>w :w<CR>
nnoremap <leader>q :q<CR>
nnoremap <leader>x :x<CR>

nnoremap <leader><leader> @

nnoremap <leader>r gq}

nnoremap <leader>sv :source ~/.vim/vimrc<CR>

"make wrapped lines more intuitive
nnoremap <silent> j gj
nnoremap <silent> k gk
nnoremap <silent> 0 g0
nnoremap <silent> $ g$

nnoremap <silent> B ge

nnoremap <C-e> :Lexplore<CR>

nnoremap J <C-e>
nnoremap K <C-y>

" highlight last inserted text
noremap gV `[v`]

noremap <leader>h :nohlsearch<CR>

noremap <leader>p "+p
noremap <leader>d "+d
noremap <leader>y "+y

noremap <leader>S :%s//g<LEFT><LEFT>
noremap <leader>s :s//g<LEFT><LEFT>

noremap <leader>l @:
noremap <CR> o<Esc>

noremap <Up> <Nop>
noremap <Down> <Nop>
noremap <Left> <Nop>
noremap <Right> <Nop>

noremap Y y$

noremap  <leader>f :call FormatBadChars()<CR>

inoremap jk <esc>

inoremap <C-e> <C-o>$
inoremap <C-a> <C-o>0
inoremap <C-d> <C-o>x

inoremap <Up> <Nop>
inoremap <Down> <Nop>
inoremap <Left> <Nop>
inoremap <Right> <Nop>

" Make DEL delete the selected text
vmap <BS> x

" navigation between splits map
map <C-h> <C-w>h
map <C-j> <C-w>j
map <C-k> <C-w>k
map <C-l> <C-w>l

cmap W w !sudo tee % >/dev/null

function! FormatBadChars()
    execute '%s/Ģ/ş/g'
    execute '%s/Ġ/İ/g'
endfunction

" ABBREVIATIONS
abbr cnslg console.log();
abbr ipdb import ipdb; ipdb.set_trace()
