if [[ -f /etc/bashrc ]]; then
    source /etc/bashrc
fi

if [[ -f /usr/share/bash-completion/bash_completion ]]; then
    source /usr/share/bash-completion/bash_completion
fi

if [ -f ~/.fzf.bash ]; then
   source ~/.fzf.bash
fi

if [ -f ~/.gpg-agent ]; then
    source ~/.gpg-agent
fi

shopt -s autocd
shopt -s cdspell
shopt -s cdable_vars
shopt -s extglob
shopt -s histappend
shopt -s checkwinsize
shopt -s globstar
shopt -s nocaseglob
shopt -s cmdhist
shopt -s lithist

stty -ixon
