#!/bin/bash

# Make vim the default editor
export EDITOR=/usr/bin/vim;

export PATH=$PATH:$HOME/.local/bin:$HOME/bin:/usr/local/go/bin

# Larger bash history (allow 32³ entries; default is 500)
export HISTSIZE=50000000;
export HISTFILESIZE=$HISTSIZE;
export HISTCONTROL=ignoreboth:erasedups

# Prefer US English and use UTF-8
export LANG="en_US.UTF-8";
export LC_ALL="en_US.UTF-8";

export GIT_PS1_SHOWDIRTYSTATE=true
export GIT_PS1_SHOWUNTRACKEDFILES=true

#export PROMPT_COMMAND="history -a; history -c; history -r; $PROMPT_COMMAND"

# if hash __git_ps1; then
#     export PS1='\w$(__git_ps1 " (%s)")\$ '
# fi

export DISABLE_HOOKS=false
