#!/bin/bash

# Make vim the default editor
export EDITOR=/usr/bin/vim;

export PATH=$PATH:$HOME/.local/bin:$HOME/bin:/usr/local/go/bin

# Prefer US English and use UTF-8
export LANG="en_US.UTF-8";
export LC_ALL="en_US.UTF-8";

export GIT_PS1_SHOWDIRTYSTATE=true
export GIT_PS1_SHOWUNTRACKEDFILES=true

export DISABLE_HOOKS=false

export PROMPT_COMMAND='echo "$(date "+%Y-%m-%d.%H:%M:%S") $(pwd) $(history 1)" >> ~/var/log/bash-history-$(date "+%Y-%m-%d").log'

if [ -f ~/.local_exports ]; then
    source ~/.local_exports
fi
